
   export const Mock_Items = [
        { "id": "1", "category": "termosuelo","stock": 4, "title": "Cable Calefactor Termosuelo", "description": "Cable de 20W/mt. Temperatura máxima de superficie 100ºC. y 2 chicotes de 10 cm para conexión. Su terminación de cable es con poliolefina reticulada térmicamente con adhesivo para evitar el ingreso de humedad, agua o agentes contaminantes.", "price": 12570, "image": "https://http2.mlstatic.com/D_NQ_NP_2X_662987-MLA43059950058_082020-F.webp" },
        { "id": "2", "category": "termosuelo","stock": 6, "title": "Termostato Wifi", "description": "Termostato digital WIFI de ambiente programable para piso eléctrico, losa radiante o caldera. Cuenta con sensor de ambiente y sensor de piso con cable de 3 metros de longitud.", "price": 6540, "image": "https://http2.mlstatic.com/D_NQ_NP_2X_894523-MLA47097213933_082021-F.webp" },
        { "id": "3", "category": "termosuelo","stock": 8, "title": "Termostato Mecanico", "description": "Fabricado en Italia por la empresa IMIT, siendo una de las marcas que utiliza materiales e ingeniería de primera calidad haciendo que el producto sea hasta 10 veces más duradero y fiable que cualquier otra marca.", "price": 3650, "image": "https://http2.mlstatic.com/D_NQ_NP_2X_607558-MLA31033795894_062019-F.webp" },
        { "id": "4", "category": "termosuelo","stock": 10, "title": "Aislante 10mm 2 Cara Aluminio", "description": "Rollo de aislante térmico e impermeable de espuma de polietileno de 10 mm con aluminizado con solapa con pegamento para una mejor fijación instalación.", "price": 5800, "image": "https://http2.mlstatic.com/D_NQ_NP_2X_712514-MLA47572261635_092021-F.webp" },
        { "id": "5", "category": "bombaDeCalor","stock": 12, "title": "Bomba De Calor Wega", "description": "Mejorás la temperatura del agua entre 24 a 40 grados.Extendés tu temporada desde octubre a abril. No consume gas, Es electrica. Es inverter, de bajo consumo", "price": 320000, "image": "https://http2.mlstatic.com/D_NQ_NP_2X_733456-MLA48822560136_012022-F.webp" },
        { "id": "6", "category": "bombaDeCalor","stock": 14, "title": "Termotanque Con Bomba De Calor", "description": "La nueva tecnología toma la energía del aire del ambiente y la traslada al agua generando un calentamiento con una eficiencia de hasta cuatro veces más que con los sistemas tradicionales", "price": 215000, "image": "https://http2.mlstatic.com/D_NQ_NP_2X_876513-MLA46212272104_052021-F.webp" },
        { "id": "7", "category": "bombaDeCalor","stock": 16, "title": "Climatizador Piscina Bomba Calor", "description": "Bomba de calor para climatizar piscinas KUSHIRO 35M3 con intercambiador de titanio, equipo eléctrico de 230V – 31.400 BTU (9.2kW). Las bombas de calor KUSHIRO con Tecnología INVERTER son equipos silenciosos que gracias a su COP promedio de 8.6", "price": 289400, "image": "https://http2.mlstatic.com/D_NQ_NP_2X_786244-MLA49234381813_022022-F.webp" },
        { "id": "8", "category": "energiaSolar","stock": 18, "title": "Kit Energia Solar Completo Autoinstalable", "description": "KIT SOLAR es la marca más confiable del mercado gracias al cuidadoso armado y a sus componentes de primera calidad. Los que hacemos KIT SOLAR cuidamos cada detalle en el armado y el dimensionado.", "price": 137000, "image": "https://http2.mlstatic.com/D_NQ_NP_2X_811286-MLA46914131752_072021-F.webp" },
        { "id": "9", "category": "energiaSolar","stock": 20, "title": "Boyero Solar 30km Compacto Más Kit De Instalación", "description": "Kit completo de instalación para boyero solar, cubre hasta 6 hectáreas. Incluye: + Vaquero solar compacto 30 km + 500 metros de hilo Eléctroplástico 7 Hebras + 100 aisladores Campanita + 30 aisladores Rienda ST esquineros", "price": 54600, "image": "https://http2.mlstatic.com/D_NQ_NP_2X_771322-MLA48495048656_122021-F.webp" },
        { "id": "10", "category": "energiaSolar","stock": 22, "title": "Kit Bomba 12 Volts C/ Panel Solar", "description": "KIT BOMBEO SOLAR CON KIT 2XPANELES SOLARES 100WP C/U - KIT200WP+ BOMBA DE AGUA 12V + CABLE MC4 8 MTS DE BAJADA + UNION MC4 2 A 1 PARA PONER LOS PANELES EN PARALELOS", "price": 60000, "image": "https://http2.mlstatic.com/D_NQ_NP_2X_916674-MLA49301222989_032022-F.webp" }
    ]
